name: club_admin
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  get: ^4.6.5
  image_picker: ^1.0.0
  flashy_tab_bar2: ^0.0.5
  google_fonts: ^5.1.0
  pinput: ^2.2.31
  firebase_storage: ^11.2.4
  geolocator: ^9.0.2
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_switch: ^0.3.2
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  http: ^1.1.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  app_settings: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf

  assets:
    - assets/icons/