// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk8LUM4zzTrys5V4YwXqniLgcGmy-bDA',
    appId: '1:1082350793346:android:5a689015e6f93a73b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:f790ae5b7332e4d3b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
    androidClientId: '1082350793346-j6k8k71k21u5gpt4299sfukdk4hg7r98.apps.googleusercontent.com',
    iosClientId: '1082350793346-2k9ve0s0co39fdh9t02amgf3b8k007jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:f69f7dc02896b53eb03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
    androidClientId: '1082350793346-j6k8k71k21u5gpt4299sfukdk4hg7r98.apps.googleusercontent.com',
    iosClientId: '1082350793346-87mjah6vpe06823gkt4r4eqli3rv4930.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubAdmin.RunnerTests',
  );
}
